# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-16 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twee_t',
            name='timestamp',
        ),
    ]
