# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20180309_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_number',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_content',
            field=models.CharField(default='write tweet here', max_length=140),
        ),
    ]
