# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20180309_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name = 'tweet',
            name = 'timestamp',
        ),
    ]
