# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20180309_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='content1',
            new_name='this_is_a_tweet',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='content4',
        ),
    ]
