# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_twee_t_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='twee_t',
            name='hashtag',
            field=models.CharField(default='put your hashtag here', max_length=160),
        ),
    ]
