# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20180322_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twee_t',
            old_name='Hashtag',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='twee_t',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='twee_t',
            old_name='Tweet_content',
            new_name='tweet_content',
        ),
        migrations.RenameField(
            model_name='twee_t',
            old_name='Updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='twee_t',
            old_name='User',
            new_name='user',
        ),
    ]
