# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20180322_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twee_t',
            old_name='City_name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='twee_t',
            old_name='College_name',
            new_name='college_name',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='State',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='twee_t',
            name='phone',
            field=models.IntegerField(default=7004602281),
        ),
        migrations.AddField(
            model_name='twee_t',
            name='state',
            field=models.CharField(default='Bihar', max_length=20),
        ),
    ]
