# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20180322_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twee_t',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='state',
        ),
    ]
