# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20180322_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='twee_t',
            name='city_name',
            field=models.CharField(default='Patna', max_length=20),
        ),
        migrations.AddField(
            model_name='twee_t',
            name='college_name',
            field=models.CharField(default='Institute if engineering and management', max_length=200),
        ),
        migrations.AddField(
            model_name='twee_t',
            name='phone',
            field=models.IntegerField(default=7004602281),
        ),
        migrations.AddField(
            model_name='twee_t',
            name='state',
            field=models.CharField(default='Bihar', max_length=20),
        ),
    ]
