# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20180322_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twee_t',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='state',
        ),
        migrations.AddField(
            model_name='twee_t',
            name='hashtag',
            field=models.CharField(default='put your hashtag here', max_length=160),
        ),
        migrations.AddField(
            model_name='twee_t',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
