# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20180322_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twee_t',
            name='phone',
            field=models.BigIntegerField(default=7004602281),
        ),
    ]
