# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_auto_20180322_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twee_t',
            name='phone',
        ),
        migrations.AddField(
            model_name='twee_t',
            name='college',
            field=models.CharField(default='put your hashtag here', max_length=160),
        ),
    ]
