# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_auto_20180322_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twee_t',
            name='hashtag',
        ),
    ]
