# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0017_auto_20180322_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twee_t',
            name='hashtag',
            field=models.CharField(default='put hashtag without #', max_length=160),
        ),
    ]
