# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0018_auto_20180322_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twee_t',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='twee_t',
            name='state',
        ),
        migrations.AlterField(
            model_name='twee_t',
            name='hashtag',
            field=models.CharField(default='put hashtag without #', max_length=160, validators=[tweets.models.validate_hashtag]),
        ),
        migrations.AlterField(
            model_name='twee_t',
            name='tweet_content',
            field=models.CharField(default='write tweet here', max_length=150, validators=[tweets.models.validate_tweet_content]),
        ),
    ]
