# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0021_auto_20180309_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 11, 6, 47, 449802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 11, 6, 47, 449802, tzinfo=utc)),
        ),
    ]
