# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0023_auto_20180309_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='updated',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
